### PR TITLE
First draft of home page

### PR DESCRIPTION
**Pull request by shekharkhedekar**

### CODE REVIEW

**Comment by shekharkhedekar** [comment]
@mrengy pls take a look

**Review by mrengy — APPROVED** [review]
So far so good. I fixed a merge conflict of style.css through the github web editor. 

I won't merge this for now since it looks as though it's still in progress, but I'm pulling it onto [dev](https://historyscv-dev.dreamhosters.com/).

**Comment by mrengy** [comment]
Or I'll let you go ahead and merge it if you see fit in your workflow.

**Comment by shekharkhedekar** [comment]
Something's up with that workflow, and I think I have a better solution - I'll run it by you tomorrow, but the gist of it is adding a `post_merge` hook that builds the scss (gets triggered on `git pull`) and adding the built css to `.gitignore`

**Pull request merged**
