### PR TITLE
Minor progress on generic pages (About/Green Feather etc)

### PR DESCRIPTION
**Pull request by shekharkhedekar**
Some progress on generic pages - basically making sure they are set with the green background and sub-element styling. Also cleans up some errant borders on non-text links

### CODE REVIEW

**Review by mrengy — APPROVED** [review]

**Comment by mrengy** [comment]
Okay, after I merged, I pulled on dev and stage. 

I was getting a conflict with the rebase earlier (involving style.css deleted in one branch but modified on the other), and I couldn't find a way around that, so instead I merged locally and got another merge conflict in the history - sorry. ;)

**Comment by mrengy** [comment]
Also, in resolving the merge conflict, I ended up making this commit that deletes style.css. c636634548022a1349a1263088b35d7bf8466dcc Do you think that's going to cause problems in the future? In the pulls I did, it got rebuilt successfully, but I'm just thinking - is there a sequence of git operations where it wouldn't get rebuilt and that would be an issue?

**Comment by shekharkhedekar** [comment]
Yeah, the best thing to do is to rebase, accept the deletion of the file, and force push. We should be good now though with the extra commit to delete the css. The only time a `git pull` will not result in a rebuild is if you are on the latest, e.g. there is nothing to pull. Unless there's something I'm not thinking of, this should be safe. Worst case we ssh in and run `npm run sass`

**Comment by mrengy** [comment]
Sounds good. I’ll leave it as is.

**Pull request merged**
