### PR TITLE
Styling Adjustments

### PR DESCRIPTION
**Pull request by shekharkhedekar**
Addresses https://3.basecamp.com/5067876/buckets/22032865/todos/5887433938 and https://3.basecamp.com/5067876/buckets/22032865/todos/5794571407

Also moved "Show Full Story" below the excerpt, because that's where the full story will appear when pressed.

### CODE REVIEW

**Review by mrengy — CHANGES_REQUESTED** [review]
Thanks! Looks good on the proportional video scaling. 

I'm not seeing: 

1. treatment of image (rounded corners, white border drop shadow) for featured story on homepage, [per Adam's comment](https://3.basecamp.com/5067876/buckets/22032865/todos/5887433938#__recording_5887450814)
2. [the adjusted desktop layout for the galleries page](https://3.basecamp.com/5067876/buckets/22032865/todos/5794571407). It's closer but still showing the gallery images in a single column. [Screenshot from this branch on stage](https://jmp.sh/qOA3MK6Y). - it displays correctly in a 3x3 grid when I activate the tewentytwentythree default theme - [screenshot](https://jmp.sh/q0tXij5B).

I exported the wp-content/uploads/2023/03 files and a database export from stage and sent you that in a Basecamp ping, so you can use that locally.

**Comment by mrengy** [comment]
Oh, I think I was viewing an old version of the CSS on stage in my earlier review comment. Now it looks closer but still showing the gallery images in a single column. I edited that earlier comment with a new screenshot to clarify. I'm leaving this branch on stage for now.

**Comment by shekharkhedekar** [comment]
> Oh, I think I was viewing an old version of the CSS on stage in my earlier review comment. Now it looks closer but still showing the gallery images in a single column. I edited that earlier comment with a new screenshot to clarify. I'm leaving this branch on stage for now.

@mrengy got it - looks like there as some extra css that was messing it up, removed it and didn't see any adverse effects on other `figure` related content

**Review by mrengy — APPROVED** [review]
Looks good. Thanks! I'll merge.

**Pull request merged**
