### PR TITLE
WIP Add build_sass workflow

### PR DESCRIPTION
**Pull request by shekharkhedekar**

### CODE REVIEW

**Comment by mrengy** [comment]
Nice idea. I'm seeing "1 failing check" in Github on the PR. Is that expected? Is that something that would be resolved when this is merged to main? 
Screen Shot 2022-12-26 at 8 27 35 PM



I get the general intent here but haven't done anything successful yet with github workflows, so I'm not sure how to correct it.

**Review by mrengy — APPROVED** [review]
I'll merge to main for now and see what happens ;)

**Comment by shekharkhedekar** [comment]
Ah this was work in progress. Can you revert and I will let you know when it’s ready

**Comment by mrengy** [comment]
Oh, right. I guess that's why you had WIP in the PR title ;). I reverted
the main branch.

**Pull request merged**
