### PR TITLE
Add Comments Styling

### PR DESCRIPTION
**Pull request by shekharkhedekar**
Screenshot 2023-01-03 at 6 36 13 PM

### CODE REVIEW

**Review by mrengy — CHANGES_REQUESTED** [review]
Nice!  Thanks for the quick work here.

In the markup, I moved the "reply" link above the horizontal line with https://github.com/mrengy/vanguard-history/pull/73/commits/82d844d4ae185464b44e1c077e82fbaf10d8432f to match the design. 

Only inconsistencies I am catching here are: the "reply" link is too small, should be aligned right, and should be red text. 

The "Leave a Reply" heading needs more vertical space above it, but I'm assuming this is just meant to address the portion you included in the screenshot and you'll get to that later.

**Comment by mrengy** [comment]
I caught one other thing about distorted profile photos and updated my review comment with that. 

Also, I pulled this branch to dev in case you'd like to look at it there.

**Comment by shekharkhedekar** [comment]
@mrengy fixed the reply stuff (class name changed) and the avatar size (weird flex box issue)

**Comment by mrengy** [comment]
Thanks! The fixes look good. 

I was getting some merge conflicts locally, and I did a reset --hard which resolved them. I got the same merge conflicts when pulling this branch to dev. I think this is due to the rebase you did, right? Do you think we will be missing any changes if I do the same reset --hard on dev? If it seems safe to do this, I'll let you merge this PR and later I'll update it on dev (I'll be traveling most of the day tomorrow).

Here's some Terminal output from dev.

[disston]$ git pull
remote: Enumerating objects: 127, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 127 (delta 37), reused 49 (delta 33), pack-reused 69
Receiving objects: 100% (127/127), 47.51 KiB | 170.00 KiB/s, done.
Resolving deltas: 100% (56/56), completed with 10 local objects.
From https://github.com/mrengy/vanguard-history
 + 82d844d...196a6fc shekhar/comments        -> origin/shekhar/comments  (forced update)
   13ac5c2..9591bbf  main                    -> origin/main
 + 914162d...2103f1f shekhar/footer          -> origin/shekhar/footer  (forced update)
 + f726891...7d9a332 shekhar/test-build-sass -> origin/shekhar/test-build-sass  (forced update)
Auto-merging wp-content/themes/vanguard-history/style.scss
CONFLICT (content): Merge conflict in wp-content/themes/vanguard-history/style.scss
Auto-merging wp-content/themes/vanguard-history/style.css
CONFLICT (content): Merge conflict in wp-content/themes/vanguard-history/style.css
Removing wp-content/themes/vanguard-history/img/RedShield.svg
Auto-merging wp-content/themes/vanguard-history/functions.php
Auto-merging wp-content/themes/vanguard-history/css/_year.scss
Auto-merging wp-content/themes/vanguard-history/css/_comments.scss
CONFLICT (add/add): Merge conflict in wp-content/themes/vanguard-history/css/_comments.scss
Automatic merge failed; fix conflicts and then commit the result.
[disston]$

**Comment by shekharkhedekar** [comment]
Once I merge to main you should be able to pull on dev/stage. I don't know why you had to reset --hard. I prefer rebasing on main to merging main in to preserve commit history and avoid ugly merge commits.  I think you need to approve the PR before I can merge

**Review by mrengy — APPROVED** [review]
Ah, got it.

**Pull request merged**
