### PR TITLE
Update site hyperlink color

### PR DESCRIPTION
**Pull request by shekharkhedekar**

### CODE REVIEW

**Comment by shekharkhedekar** [comment]
@mrengy pls take a look

**Review by mrengy — APPROVED** [review]
Nice. I thought we discussed making the hover color black - otherwise, the red is invisible on the year story background. I changed this with https://github.com/mrengy/vanguard-history/pull/82/commits/9c0300e1290c756a32d9fec794415ff7767b5bda . Feel free to modify elsewhere in the code if needed.

**Comment by mrengy** [comment]
I'm getting failed checks on the build sass workflow https://github.com/mrengy/vanguard-history/actions/runs/3955150623/jobs/6773177593 . I am also seeing similar things locally (there's a merge conflict or two that I fixed locally after following [these commands to rebase](https://github.com/mrengy/vanguard-history#to-get-updates-from-other-team-members) and then force pushed). These merge conflicts seem to be following me from branch to branch, not sure why.

Here's what I'm seeing locally in my Terminal

> mikeeng@Mike-Eng-MacBook-Pro public % git checkout main
> Switched to branch 'main'
> Your branch is up to date with 'origin/main'.
> mikeeng@Mike-Eng-MacBook-Pro public % git pull
> Already up to date.
> mikeeng@Mike-Eng-MacBook-Pro public % git checkout shekhar/hyperlink                               
> error: Your local changes to the following files would be overwritten by checkout:
> 	wp-content/themes/vanguard-history/style.css
> Please commit your changes or stash them before you switch branches.
> Aborting
> mikeeng@Mike-Eng-MacBook-Pro public % git stash
> Saved working directory and index state WIP on main: 231b1c3 Merge pull request #84 from mrengy/shekhar/burger-menu-update
> mikeeng@Mike-Eng-MacBook-Pro public % git checkout shekhar/hyperlink
> Switched to branch 'shekhar/hyperlink'
> Your branch is up to date with 'origin/shekhar/hyperlink'.
> mikeeng@Mike-Eng-MacBook-Pro public % git pull
> Already up to date.
> mikeeng@Mike-Eng-MacBook-Pro public % git rebase main
> Auto-merging wp-content/themes/vanguard-history/css/_header.scss
> CONFLICT (content): Merge conflict in wp-content/themes/vanguard-history/css/_header.scss
> Auto-merging wp-content/themes/vanguard-history/style.css
> CONFLICT (content): Merge conflict in wp-content/themes/vanguard-history/style.css
> error: could not apply 130adde... Update site hyperlink color
> hint: Resolve all conflicts manually, mark them as resolved with
> hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
> hint: You can instead skip this commit: run "git rebase --skip".
> hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
> Could not apply 130adde... Update site hyperlink color
> mikeeng@Mike-Eng-MacBook-Pro public % git add .
> mikeeng@Mike-Eng-MacBook-Pro public % git add .            
> mikeeng@Mike-Eng-MacBook-Pro public % git rebase --continue
> [detached HEAD fade223] Update site hyperlink color
>  Author: shekharkhedekar <shekhar.khedekar@gmail.com>
>  5 files changed, 23 insertions(+), 15 deletions(-)
> Successfully rebased and updated refs/heads/shekhar/hyperlink.
> mikeeng@Mike-Eng-MacBook-Pro public % git push -f
> Enumerating objects: 30, done.
> Counting objects: 100% (30/30), done.
> Delta compression using up to 12 threads
> Compressing objects: 100% (18/18), done.
> Writing objects: 100% (20/20), 2.41 KiB | 2.41 MiB/s, done.
> Total 20 (delta 13), reused 0 (delta 0), pack-reused 0
> remote: Resolving deltas: 100% (13/13), completed with 8 local objects.
> To github.com:mrengy/vanguard-history.git
>  + 9c0300e...e611fdc shekhar/hyperlink -> shekhar/hyperlink (forced update)
> mikeeng@Mike-Eng-MacBook-Pro public % 
>

**Comment by mrengy** [comment]
And then when I checkout and pull main, I get

> mikeeng@Mike-Eng-MacBook-Pro public % git push -f
> Enumerating objects: 30, done.
> Counting objects: 100% (30/30), done.
> Delta compression using up to 12 threads
> Compressing objects: 100% (18/18), done.
> Writing objects: 100% (20/20), 2.41 KiB | 2.41 MiB/s, done.
> Total 20 (delta 13), reused 0 (delta 0), pack-reused 0
> remote: Resolving deltas: 100% (13/13), completed with 8 local objects.
> To github.com:mrengy/vanguard-history.git
>  + 9c0300e...e611fdc shekhar/hyperlink -> shekhar/hyperlink (forced update)
> mikeeng@Mike-Eng-MacBook-Pro public % git checkout main
> Switched to branch 'main'
> Your branch is up to date with 'origin/main'.
> mikeeng@Mike-Eng-MacBook-Pro public % git pull
> remote: Enumerating objects: 1, done.
> remote: Counting objects: 100% (1/1), done.
> remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
> Unpacking objects: 100% (1/1), 685 bytes | 685.00 KiB/s, done.
> From github.com:mrengy/vanguard-history
>    231b1c3..21696be  main       -> origin/main
> Updating 231b1c3..21696be
> error: Your local changes to the following files would be overwritten by merge:
> 	wp-content/themes/vanguard-history/style.css
> Please commit your changes or stash them before you merge.
> Aborting
> mikeeng@Mike-Eng-MacBook-Pro public %

**Comment by mrengy** [comment]
Re: merge conflicts seem to be following me from branch to branch,

The SCSS merge conflicts didn't follow me to the last branch I reviewed (the homepage one), so nevermind. There was still the style.css conflict which I am seeing both in GitHub and locally, but that's no big deal to resolve each time.

**Pull request merged**
