### PR TITLE
Build CSS Workflow

### PR DESCRIPTION
**Pull request by shekharkhedekar**

### CODE REVIEW

**Comment by shekharkhedekar** [comment]
@mrengy ok this should be ready now

**Comment by mrengy** [comment]
Looks as though you're having fun ;). Do you want me to merge this into main?

**Comment by shekharkhedekar** [comment]
> Looks as though you're having fun ;). Do you want me to merge this into main?

Not yet! Will let you know

**Comment by shekharkhedekar** [comment]
Alright I think we're good to go @mrengy

**Comment by shekharkhedekar** [comment]
I still haven't figured out how to make the commit history nicer (getting rid of the blank commit) but it works

**Comment by mrengy** [comment]
Great! I deployed to the dev and stage sites.
--

**Pull request merged**
