### PR TITLE
Incremental media loading

### PR DESCRIPTION
**Pull request by shekharkhedekar**
Addresses https://3.basecamp.com/5067876/buckets/22032865/todos/5881611106. 

Currently, we are using `limit=6`, so we fetch 6 at a time, but this can be changed pretty quickly.

### CODE REVIEW

**Comment by mrengy** [comment]
Also, I could take care of those changes if needed - let me know.

**Comment by shekharkhedekar** [comment]
> On the right track. Thank you! The button is now incrementally loading additional images, and it seems to be not missing or duplicating any. [Screen recording](https://jmp.sh/RtL1SJgr).
> 
> Also I put this branch on dev and added more media to [2001 SCV there](https://historyscv-dev.dreamhosters.com/year_story/2001-scv/) to test.
> 
> Some things:
> 
> Need to remove / modify the .content-secondary-grid a:nth-child(n+7){ display:none } - looks to me as though it's on line 177 of _content.scss .
> 
> Change the button text from "show all media" to "show more media"
> 
> (optional) perhaps a "view all" link next to the "Media" heading - going to the All Media page with the appropriate vhs_year and ensemble set - but don't worry about that if you're pressed for time.

Confused: I did all of the above except for View All.

**Comment by mrengy** [comment]
Oh, I see. My bad. I was missing some css because I didn't compile it. I compiled now on dev. So that resolves the hidden items past the 7th child.

Still not seeing the change in the button text from "show all media" to "show more media"

**Comment by shekharkhedekar** [comment]
Yup, missed that. Updated.

**Review by mrengy — APPROVED** [review]

**Comment by mrengy** [comment]
Thanks for resolving all of the required things! I'll work on the prod migration now.

**Pull request merged**
